/**
 * Sovereign Empire QA Checklist Module
 *
 * Codifies every validation check from the QA specification into typed,
 * queryable data structures. Pure TypeScript with no database access or
 * external imports. Each QaCheck maps to a single testable assertion that
 * must pass before the platform (or a specific phase) is considered ready.
 *
 * Sections 1-7 correspond to build phases 1-7.
 * Sections 8-10 are recurring audits (full system, pre-onboard, monthly).
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type QaVerdict = "pass" | "warning" | "fail";

export type QaSection =
  | "foundation"
  | "discovery"
  | "outreach"
  | "billing_client_ops"
  | "reporting_dashboard"
  | "acquisition"
  | "advanced_features"
  | "full_system"
  | "pre_onboard"
  | "monthly_health";

export type QaSubsection = string;

export interface QaCheck {
  id: string;
  section: QaSection;
  subsection: QaSubsection;
  label: string;
  critical: boolean;
  automatable: boolean;
  order: number;
}

export interface QaCheckResult {
  checkId: string;
  verdict: QaVerdict;
  detail?: string;
}

export interface QaSectionMeta {
  section: QaSection;
  name: string;
  description: string;
  phase: number | null;
  runWhen: string;
}

// ---------------------------------------------------------------------------
// Section metadata
// ---------------------------------------------------------------------------

export const QA_SECTIONS: QaSectionMeta[] = [
  {
    section: "foundation",
    name: "Foundation Audit",
    description:
      "Environment, database, core libraries, and Telegram bot health checks.",
    phase: 1,
    runWhen: "after_phase_1",
  },
  {
    section: "discovery",
    name: "Discovery Audit",
    description:
      "Orchestrator, enrichment pipeline, and lead scoring validation.",
    phase: 2,
    runWhen: "after_phase_2",
  },
  {
    section: "outreach",
    name: "Outreach Audit",
    description:
      "Compliance (CAN-SPAM, TCPA, voice, data privacy), personalizer, senders, follow-up FSM, and reply responder.",
    phase: 3,
    runWhen: "after_phase_3",
  },
  {
    section: "billing_client_ops",
    name: "Billing & Client Ops Audit",
    description:
      "Stripe integration, onboarding flow, and client management checks.",
    phase: 4,
    runWhen: "after_phase_4",
  },
  {
    section: "reporting_dashboard",
    name: "Reporting & Dashboard Audit",
    description: "Report generation and dashboard UI/UX validation.",
    phase: 5,
    runWhen: "after_phase_5",
  },
  {
    section: "acquisition",
    name: "Acquisition Audit",
    description:
      "Contractor acquisition pipeline, proposals, proof engine, and referral tracking.",
    phase: 6,
    runWhen: "after_phase_6",
  },
  {
    section: "advanced_features",
    name: "Advanced Features Audit",
    description:
      "Voice receptionist, review management, funnel renderer, CRM push, and multi-location routing.",
    phase: 7,
    runWhen: "after_phase_7",
  },
  {
    section: "full_system",
    name: "Full System Audit",
    description:
      "End-to-end pipeline walkthrough, failure mode testing, and performance benchmarks.",
    phase: null,
    runWhen: "before_first_client",
  },
  {
    section: "pre_onboard",
    name: "Pre-Onboard Check",
    description:
      "Per-client readiness verification before activating a new contractor account.",
    phase: null,
    runWhen: "before_each_onboard",
  },
  {
    section: "monthly_health",
    name: "Monthly Health & Drift Check",
    description:
      "Code quality, data quality, cost tracking, security, compliance, and performance drift monitoring.",
    phase: null,
    runWhen: "monthly",
  },
];

// ---------------------------------------------------------------------------
// Checks
// ---------------------------------------------------------------------------

export const QA_CHECKS: QaCheck[] = [
  // =======================================================================
  // Section 1 — Foundation
  // =======================================================================

  // ── environment ──
  {
    id: "f_env_example_exists",
    section: "foundation",
    subsection: "environment",
    label: ".env.example exists",
    critical: false,
    automatable: true,
    order: 1,
  },
  {
    id: "f_env_gitignore",
    section: "foundation",
    subsection: "environment",
    label: ".env is in .gitignore",
    critical: true,
    automatable: true,
    order: 2,
  },
  {
    id: "f_no_hardcoded_secrets",
    section: "foundation",
    subsection: "environment",
    label: "No hardcoded secrets in source code",
    critical: true,
    automatable: true,
    order: 3,
  },
  {
    id: "f_no_secrets_in_logs",
    section: "foundation",
    subsection: "environment",
    label: "No secrets appear in log output",
    critical: true,
    automatable: true,
    order: 4,
  },
  {
    id: "f_config_loads_defaults",
    section: "foundation",
    subsection: "environment",
    label: "Config loads environment variables with defaults",
    critical: false,
    automatable: true,
    order: 5,
  },
  {
    id: "f_config_raises_missing",
    section: "foundation",
    subsection: "environment",
    label: "Config raises on missing required vars",
    critical: false,
    automatable: true,
    order: 6,
  },
  {
    id: "f_config_values_typed",
    section: "foundation",
    subsection: "environment",
    label: "All config values typed",
    critical: false,
    automatable: true,
    order: 7,
  },

  // ── database ──
  {
    id: "f_db_tables_exist",
    section: "foundation",
    subsection: "database",
    label: "All tables exist",
    critical: true,
    automatable: true,
    order: 8,
  },
  {
    id: "f_db_indexes_created",
    section: "foundation",
    subsection: "database",
    label: "Indexes created",
    critical: false,
    automatable: true,
    order: 9,
  },
  {
    id: "f_db_rls_enabled",
    section: "foundation",
    subsection: "database",
    label: "RLS enabled on all tables",
    critical: true,
    automatable: true,
    order: 10,
  },
  {
    id: "f_db_rls_policies_work",
    section: "foundation",
    subsection: "database",
    label: "RLS policies enforce correct access",
    critical: true,
    automatable: true,
    order: 11,
  },
  {
    id: "f_db_migrations_idempotent",
    section: "foundation",
    subsection: "database",
    label: "Migrations are idempotent",
    critical: false,
    automatable: true,
    order: 12,
  },
  {
    id: "f_db_foreign_keys",
    section: "foundation",
    subsection: "database",
    label: "Foreign keys in place",
    critical: false,
    automatable: true,
    order: 13,
  },
  {
    id: "f_db_no_orphans",
    section: "foundation",
    subsection: "database",
    label: "No orphaned records possible",
    critical: false,
    automatable: true,
    order: 14,
  },
  {
    id: "f_db_connection_pooling",
    section: "foundation",
    subsection: "database",
    label: "Connection pooling configured",
    critical: false,
    automatable: true,
    order: 15,
  },
  {
    id: "f_db_health_check",
    section: "foundation",
    subsection: "database",
    label: "Health check endpoint works",
    critical: true,
    automatable: true,
    order: 16,
  },

  // ── claude_lib ──
  {
    id: "f_claude_retry_429_500_503",
    section: "foundation",
    subsection: "claude_lib",
    label: "Retries on 429/500/503",
    critical: false,
    automatable: true,
    order: 17,
  },
  {
    id: "f_claude_exponential_backoff",
    section: "foundation",
    subsection: "claude_lib",
    label: "Exponential backoff on retries",
    critical: false,
    automatable: true,
    order: 18,
  },
  {
    id: "f_claude_cache_hit",
    section: "foundation",
    subsection: "claude_lib",
    label: "Cache hit on identical prompt",
    critical: false,
    automatable: true,
    order: 19,
  },
  {
    id: "f_claude_cache_expires",
    section: "foundation",
    subsection: "claude_lib",
    label: "Cache expires after TTL",
    critical: false,
    automatable: true,
    order: 20,
  },
  {
    id: "f_claude_token_tracking",
    section: "foundation",
    subsection: "claude_lib",
    label: "Token tracking recorded",
    critical: false,
    automatable: true,
    order: 21,
  },
  {
    id: "f_claude_budget_cap",
    section: "foundation",
    subsection: "claude_lib",
    label: "Budget cap blocks further requests",
    critical: true,
    automatable: true,
    order: 22,
  },
  {
    id: "f_claude_haiku_fast",
    section: "foundation",
    subsection: "claude_lib",
    label: "ask_claude_fast uses Haiku model",
    critical: false,
    automatable: true,
    order: 23,
  },
  {
    id: "f_claude_empty_on_exhausted",
    section: "foundation",
    subsection: "claude_lib",
    label: "Returns empty string on exhausted retries",
    critical: false,
    automatable: true,
    order: 24,
  },
  {
    id: "f_claude_no_pii_logging",
    section: "foundation",
    subsection: "claude_lib",
    label: "No PII in prompt logging",
    critical: true,
    automatable: true,
    order: 25,
  },

  // ── supabase_lib ──
  {
    id: "f_supa_connection_succeeds",
    section: "foundation",
    subsection: "supabase_lib",
    label: "Connection succeeds",
    critical: true,
    automatable: true,
    order: 26,
  },
  {
    id: "f_supa_health_check",
    section: "foundation",
    subsection: "supabase_lib",
    label: "Health check works",
    critical: true,
    automatable: true,
    order: 27,
  },
  {
    id: "f_supa_helpers_common",
    section: "foundation",
    subsection: "supabase_lib",
    label: "Helpers handle common queries",
    critical: false,
    automatable: true,
    order: 28,
  },
  {
    id: "f_supa_error_handling",
    section: "foundation",
    subsection: "supabase_lib",
    label: "Error handling on failure",
    critical: false,
    automatable: true,
    order: 29,
  },

  // ── logger_lib ──
  {
    id: "f_log_structured_json",
    section: "foundation",
    subsection: "logger_lib",
    label: "Structured JSON output",
    critical: false,
    automatable: true,
    order: 30,
  },
  {
    id: "f_log_console_supabase",
    section: "foundation",
    subsection: "logger_lib",
    label: "Logs to console and Supabase",
    critical: false,
    automatable: true,
    order: 31,
  },
  {
    id: "f_log_no_pii",
    section: "foundation",
    subsection: "logger_lib",
    label: "No PII in logs",
    critical: true,
    automatable: true,
    order: 32,
  },
  {
    id: "f_log_levels_correct",
    section: "foundation",
    subsection: "logger_lib",
    label: "Log levels correct",
    critical: false,
    automatable: true,
    order: 33,
  },
  {
    id: "f_log_telegram_on_error",
    section: "foundation",
    subsection: "logger_lib",
    label: "Telegram alert on error/critical",
    critical: false,
    automatable: true,
    order: 34,
  },

  // ── telegram_lib ──
  {
    id: "f_tg_send_message",
    section: "foundation",
    subsection: "telegram_lib",
    label: "Send message works",
    critical: false,
    automatable: true,
    order: 35,
  },
  {
    id: "f_tg_alert_tiers",
    section: "foundation",
    subsection: "telegram_lib",
    label: "Alert tiers work",
    critical: false,
    automatable: true,
    order: 36,
  },
  {
    id: "f_tg_message_truncation",
    section: "foundation",
    subsection: "telegram_lib",
    label: "Message truncation on long content",
    critical: false,
    automatable: true,
    order: 37,
  },
  {
    id: "f_tg_retry_on_failure",
    section: "foundation",
    subsection: "telegram_lib",
    label: "Retry on failure",
    critical: false,
    automatable: true,
    order: 38,
  },

  // ── telegram_bot ──
  {
    id: "f_bot_status_real_health",
    section: "foundation",
    subsection: "telegram_bot",
    label: "/status returns real health data",
    critical: false,
    automatable: true,
    order: 39,
  },
  {
    id: "f_bot_health_subsystems",
    section: "foundation",
    subsection: "telegram_bot",
    label: "/health checks all subsystems",
    critical: false,
    automatable: true,
    order: 40,
  },
  {
    id: "f_bot_responds_3s",
    section: "foundation",
    subsection: "telegram_bot",
    label: "Responds within 3 seconds",
    critical: false,
    automatable: true,
    order: 41,
  },
  {
    id: "f_bot_unknown_cmd_help",
    section: "foundation",
    subsection: "telegram_bot",
    label: "Unknown commands return help text",
    critical: false,
    automatable: true,
    order: 42,
  },
  {
    id: "f_bot_no_crash_malformed",
    section: "foundation",
    subsection: "telegram_bot",
    label: "Does not crash on malformed input",
    critical: false,
    automatable: true,
    order: 43,
  },
  {
    id: "f_bot_auth_operator",
    section: "foundation",
    subsection: "telegram_bot",
    label: "Auth check on operator chat ID",
    critical: true,
    automatable: true,
    order: 44,
  },

  // =======================================================================
  // Section 2 — Discovery
  // =======================================================================

  // ── orchestrator ──
  {
    id: "d_orch_runs_no_error",
    section: "discovery",
    subsection: "orchestrator",
    label: "Runs without error",
    critical: false,
    automatable: true,
    order: 1,
  },
  {
    id: "d_orch_structured_data",
    section: "discovery",
    subsection: "orchestrator",
    label: "Returns structured data",
    critical: false,
    automatable: true,
    order: 2,
  },
  {
    id: "d_orch_unreachable_source",
    section: "discovery",
    subsection: "orchestrator",
    label: "Handles unreachable source gracefully",
    critical: false,
    automatable: true,
    order: 3,
  },
  {
    id: "d_orch_rate_limits",
    section: "discovery",
    subsection: "orchestrator",
    label: "Respects rate limits",
    critical: false,
    automatable: true,
    order: 4,
  },
  {
    id: "d_orch_deduplicates",
    section: "discovery",
    subsection: "orchestrator",
    label: "Deduplicates discovered leads",
    critical: false,
    automatable: true,
    order: 5,
  },
  {
    id: "d_orch_logs_results",
    section: "discovery",
    subsection: "orchestrator",
    label: "Logs results",
    critical: false,
    automatable: true,
    order: 6,
  },
  {
    id: "d_orch_dry_run",
    section: "discovery",
    subsection: "orchestrator",
    label: "Dry-run mode works",
    critical: false,
    automatable: true,
    order: 7,
  },

  // ── enrichment ──
  {
    id: "d_enrich_processes_discovered",
    section: "discovery",
    subsection: "enrichment",
    label: "Processes leads in discovered status",
    critical: false,
    automatable: true,
    order: 8,
  },
  {
    id: "d_enrich_updates_data",
    section: "discovery",
    subsection: "enrichment",
    label: "Updates lead with enrichment data",
    critical: false,
    automatable: true,
    order: 9,
  },
  {
    id: "d_enrich_moves_enriched",
    section: "discovery",
    subsection: "enrichment",
    label: "Moves lead to enriched status",
    critical: false,
    automatable: true,
    order: 10,
  },
  {
    id: "d_enrich_no_data_loss",
    section: "discovery",
    subsection: "enrichment",
    label: "Does not lose data on enrichment failure",
    critical: false,
    automatable: true,
    order: 11,
  },
  {
    id: "d_enrich_handles_missing",
    section: "discovery",
    subsection: "enrichment",
    label: "Handles missing data gracefully",
    critical: false,
    automatable: true,
    order: 12,
  },

  // ── scoring ──
  {
    id: "d_score_range_0_100",
    section: "discovery",
    subsection: "scoring",
    label: "Score range is 0-100",
    critical: false,
    automatable: true,
    order: 13,
  },
  {
    id: "d_score_weights_match_spec",
    section: "discovery",
    subsection: "scoring",
    label: "Weights match specification",
    critical: false,
    automatable: true,
    order: 14,
  },
  {
    id: "d_score_breakdown_jsonb",
    section: "discovery",
    subsection: "scoring",
    label: "Breakdown stored in JSONB column",
    critical: false,
    automatable: true,
    order: 15,
  },
  {
    id: "d_score_rescoring_works",
    section: "discovery",
    subsection: "scoring",
    label: "Re-scoring produces updated results",
    critical: false,
    automatable: true,
    order: 16,
  },
  {
    id: "d_score_threshold_status",
    section: "discovery",
    subsection: "scoring",
    label: "Above-threshold leads move to correct status",
    critical: false,
    automatable: true,
    order: 17,
  },

  // =======================================================================
  // Section 3 — Outreach
  // =======================================================================

  // ── compliance_canspam ──
  {
    id: "o_canspam_physical_address",
    section: "outreach",
    subsection: "compliance_canspam",
    label: "Physical address present in email template",
    critical: true,
    automatable: true,
    order: 1,
  },
  {
    id: "o_canspam_unsubscribe_link",
    section: "outreach",
    subsection: "compliance_canspam",
    label: "Unsubscribe link present",
    critical: true,
    automatable: true,
    order: 2,
  },
  {
    id: "o_canspam_unsubscribe_works",
    section: "outreach",
    subsection: "compliance_canspam",
    label: "Unsubscribe link actually works",
    critical: true,
    automatable: true,
    order: 3,
  },
  {
    id: "o_canspam_opted_out_never_emailed",
    section: "outreach",
    subsection: "compliance_canspam",
    label: "Opted-out leads are never emailed",
    critical: true,
    automatable: true,
    order: 4,
  },
  {
    id: "o_canspam_unsubscribe_instant",
    section: "outreach",
    subsection: "compliance_canspam",
    label: "Unsubscribe takes effect instantly",
    critical: true,
    automatable: true,
    order: 5,
  },
  {
    id: "o_canspam_subject_validation",
    section: "outreach",
    subsection: "compliance_canspam",
    label: "Subject line validation (no deception)",
    critical: true,
    automatable: false,
    order: 6,
  },
  {
    id: "o_canspam_from_accuracy",
    section: "outreach",
    subsection: "compliance_canspam",
    label: "From address is accurate",
    critical: true,
    automatable: true,
    order: 7,
  },
  {
    id: "o_canspam_commercial_disclosed",
    section: "outreach",
    subsection: "compliance_canspam",
    label: "Commercial intent disclosed",
    critical: true,
    automatable: false,
    order: 8,
  },

  // ── compliance_tcpa ──
  {
    id: "o_tcpa_consent_before_sms",
    section: "outreach",
    subsection: "compliance_tcpa",
    label: "Consent obtained before SMS",
    critical: true,
    automatable: true,
    order: 9,
  },
  {
    id: "o_tcpa_stop_text",
    section: "outreach",
    subsection: "compliance_tcpa",
    label: "STOP instruction included in SMS",
    critical: true,
    automatable: true,
    order: 10,
  },
  {
    id: "o_tcpa_stop_processed",
    section: "outreach",
    subsection: "compliance_tcpa",
    label: "STOP processed instantly",
    critical: true,
    automatable: true,
    order: 11,
  },
  {
    id: "o_tcpa_opted_out_never_sms",
    section: "outreach",
    subsection: "compliance_tcpa",
    label: "Opted-out leads never receive SMS",
    critical: true,
    automatable: true,
    order: 12,
  },
  {
    id: "o_tcpa_no_sms_outside_hours",
    section: "outreach",
    subsection: "compliance_tcpa",
    label: "No SMS before 8am or after 9pm",
    critical: true,
    automatable: true,
    order: 13,
  },
  {
    id: "o_tcpa_timezone_detection",
    section: "outreach",
    subsection: "compliance_tcpa",
    label: "Timezone detection for send windows",
    critical: true,
    automatable: true,
    order: 14,
  },
  {
    id: "o_tcpa_dnc_check",
    section: "outreach",
    subsection: "compliance_tcpa",
    label: "DNC list check called before contact",
    critical: true,
    automatable: true,
    order: 15,
  },
  {
    id: "o_tcpa_attempts_tracked",
    section: "outreach",
    subsection: "compliance_tcpa",
    label: "Attempts tracked (max 3 + 30-day cooldown)",
    critical: true,
    automatable: true,
    order: 16,
  },
  {
    id: "o_tcpa_cooldown_blocks",
    section: "outreach",
    subsection: "compliance_tcpa",
    label: "Cooldown period blocks further contact",
    critical: true,
    automatable: true,
    order: 17,
  },

  // ── compliance_voice ──
  {
    id: "o_voice_real_caller_id",
    section: "outreach",
    subsection: "compliance_voice",
    label: "Real business caller ID displayed",
    critical: true,
    automatable: true,
    order: 18,
  },
  {
    id: "o_voice_ai_identifies",
    section: "outreach",
    subsection: "compliance_voice",
    label: "AI identifies itself as AI",
    critical: true,
    automatable: false,
    order: 19,
  },
  {
    id: "o_voice_recording_disclosure",
    section: "outreach",
    subsection: "compliance_voice",
    label: "Recording disclosure provided",
    critical: true,
    automatable: false,
    order: 20,
  },
  {
    id: "o_voice_dnc_suppression",
    section: "outreach",
    subsection: "compliance_voice",
    label: "DNC request during call triggers suppression",
    critical: true,
    automatable: true,
    order: 21,
  },

  // ── compliance_data_privacy ──
  {
    id: "o_privacy_pii_encrypted_rest",
    section: "outreach",
    subsection: "compliance_data_privacy",
    label: "PII encrypted at rest",
    critical: true,
    automatable: true,
    order: 22,
  },
  {
    id: "o_privacy_pii_decrypt_needed",
    section: "outreach",
    subsection: "compliance_data_privacy",
    label: "PII decrypted only when needed",
    critical: true,
    automatable: true,
    order: 23,
  },
  {
    id: "o_privacy_client_isolation",
    section: "outreach",
    subsection: "compliance_data_privacy",
    label: "Client data isolation enforced",
    critical: true,
    automatable: true,
    order: 24,
  },
  {
    id: "o_privacy_data_export",
    section: "outreach",
    subsection: "compliance_data_privacy",
    label: "Data export works",
    critical: true,
    automatable: true,
    order: 25,
  },
  {
    id: "o_privacy_data_deletion",
    section: "outreach",
    subsection: "compliance_data_privacy",
    label: "Data deletion works",
    critical: true,
    automatable: true,
    order: 26,
  },
  {
    id: "o_privacy_90d_purge",
    section: "outreach",
    subsection: "compliance_data_privacy",
    label: "90-day auto-purge runs",
    critical: true,
    automatable: true,
    order: 27,
  },

  // ── personalizer ──
  {
    id: "o_pers_unique_messages",
    section: "outreach",
    subsection: "personalizer",
    label: "Generates unique messages per lead",
    critical: false,
    automatable: true,
    order: 28,
  },
  {
    id: "o_pers_references_lead_data",
    section: "outreach",
    subsection: "personalizer",
    label: "References lead-specific data",
    critical: false,
    automatable: false,
    order: 29,
  },
  {
    id: "o_pers_brand_voice",
    section: "outreach",
    subsection: "personalizer",
    label: "Matches configured brand voice",
    critical: false,
    automatable: false,
    order: 30,
  },
  {
    id: "o_pers_compliance_check",
    section: "outreach",
    subsection: "personalizer",
    label: "Compliance check after generation",
    critical: true,
    automatable: true,
    order: 31,
  },
  {
    id: "o_pers_fallback_on_fail",
    section: "outreach",
    subsection: "personalizer",
    label: "Fallback template on Claude failure",
    critical: false,
    automatable: true,
    order: 32,
  },
  {
    id: "o_pers_ab_variants_differ",
    section: "outreach",
    subsection: "personalizer",
    label: "A/B variants are meaningfully different",
    critical: false,
    automatable: false,
    order: 33,
  },

  // ── email_sender ──
  {
    id: "o_email_warmup_respected",
    section: "outreach",
    subsection: "email_sender",
    label: "Email warmup schedule respected",
    critical: false,
    automatable: true,
    order: 34,
  },
  {
    id: "o_email_throttle_enforced",
    section: "outreach",
    subsection: "email_sender",
    label: "Throttle limits enforced",
    critical: false,
    automatable: true,
    order: 35,
  },
  {
    id: "o_email_bounce_handling",
    section: "outreach",
    subsection: "email_sender",
    label: "Bounce handling updates lead status",
    critical: false,
    automatable: true,
    order: 36,
  },
  {
    id: "o_email_open_tracking",
    section: "outreach",
    subsection: "email_sender",
    label: "Open tracking pixel works",
    critical: false,
    automatable: true,
    order: 37,
  },
  {
    id: "o_email_click_tracking",
    section: "outreach",
    subsection: "email_sender",
    label: "Click tracking works",
    critical: false,
    automatable: true,
    order: 38,
  },
  {
    id: "o_email_one_click_unsub",
    section: "outreach",
    subsection: "email_sender",
    label: "One-click unsubscribe header present",
    critical: true,
    automatable: true,
    order: 39,
  },

  // ── sms_sender ──
  {
    id: "o_sms_warmup_respected",
    section: "outreach",
    subsection: "sms_sender",
    label: "SMS warmup schedule respected",
    critical: false,
    automatable: true,
    order: 40,
  },
  {
    id: "o_sms_char_count_split",
    section: "outreach",
    subsection: "sms_sender",
    label: "Character count and segment splitting correct",
    critical: false,
    automatable: true,
    order: 41,
  },
  {
    id: "o_sms_delivery_tracking",
    section: "outreach",
    subsection: "sms_sender",
    label: "Delivery status tracking works",
    critical: false,
    automatable: true,
    order: 42,
  },
  {
    id: "o_sms_failed_retry",
    section: "outreach",
    subsection: "sms_sender",
    label: "Failed sends are retried",
    critical: false,
    automatable: true,
    order: 43,
  },

  // ── followup_state_machine ──
  {
    id: "o_fsm_correct_sequence",
    section: "outreach",
    subsection: "followup_state_machine",
    label: "Correct follow-up sequence fires",
    critical: false,
    automatable: true,
    order: 44,
  },
  {
    id: "o_fsm_channel_escalation",
    section: "outreach",
    subsection: "followup_state_machine",
    label: "Channel escalation works (email -> SMS -> etc.)",
    critical: false,
    automatable: true,
    order: 45,
  },
  {
    id: "o_fsm_engagement_triggers",
    section: "outreach",
    subsection: "followup_state_machine",
    label: "Engagement events trigger appropriate responses",
    critical: false,
    automatable: true,
    order: 46,
  },
  {
    id: "o_fsm_stops_correctly",
    section: "outreach",
    subsection: "followup_state_machine",
    label: "Stops on reply, opt-out, max attempts, or conversion",
    critical: true,
    automatable: true,
    order: 47,
  },
  {
    id: "o_fsm_no_restart_after_complete",
    section: "outreach",
    subsection: "followup_state_machine",
    label: "No restart after sequence completion",
    critical: true,
    automatable: true,
    order: 48,
  },
  {
    id: "o_fsm_cooldown_enforced",
    section: "outreach",
    subsection: "followup_state_machine",
    label: "Cooldown period enforced between sequences",
    critical: true,
    automatable: true,
    order: 49,
  },

  // ── reply_responder ──
  {
    id: "o_reply_classifies_correctly",
    section: "outreach",
    subsection: "reply_responder",
    label: "Classifies reply intent correctly",
    critical: false,
    automatable: false,
    order: 50,
  },
  {
    id: "o_reply_auto_responses",
    section: "outreach",
    subsection: "reply_responder",
    label: "Auto-responses are appropriate",
    critical: false,
    automatable: false,
    order: 51,
  },
  {
    id: "o_reply_needs_human_flags",
    section: "outreach",
    subsection: "reply_responder",
    label: "needs_human flag triggers alert",
    critical: false,
    automatable: true,
    order: 52,
  },
  {
    id: "o_reply_hot_lead_alert",
    section: "outreach",
    subsection: "reply_responder",
    label: "Hot leads alert contractor via Telegram",
    critical: false,
    automatable: true,
    order: 53,
  },
  {
    id: "o_reply_optout_suppression",
    section: "outreach",
    subsection: "reply_responder",
    label: "Opt-out reply triggers suppression",
    critical: true,
    automatable: true,
    order: 54,
  },
  {
    id: "o_reply_angry_to_human",
    section: "outreach",
    subsection: "reply_responder",
    label: "Angry replies routed to human operator",
    critical: false,
    automatable: false,
    order: 55,
  },

  // =======================================================================
  // Section 4 — Billing & Client Ops
  // =======================================================================

  // ── stripe ──
  {
    id: "b_stripe_sub_create",
    section: "billing_client_ops",
    subsection: "stripe",
    label: "Subscriptions create correctly",
    critical: true,
    automatable: true,
    order: 1,
  },
  {
    id: "b_stripe_setup_fees",
    section: "billing_client_ops",
    subsection: "stripe",
    label: "Setup fees charged correctly",
    critical: true,
    automatable: true,
    order: 2,
  },
  {
    id: "b_stripe_metered_usage",
    section: "billing_client_ops",
    subsection: "stripe",
    label: "Metered usage reported",
    critical: true,
    automatable: true,
    order: 3,
  },
  {
    id: "b_stripe_overage_billing",
    section: "billing_client_ops",
    subsection: "stripe",
    label: "Overage billing works",
    critical: true,
    automatable: true,
    order: 4,
  },
  {
    id: "b_stripe_webhook_verify",
    section: "billing_client_ops",
    subsection: "stripe",
    label: "Webhook signature verification",
    critical: true,
    automatable: true,
    order: 5,
  },
  {
    id: "b_stripe_payment_succeeded",
    section: "billing_client_ops",
    subsection: "stripe",
    label: "payment_succeeded event logged",
    critical: false,
    automatable: true,
    order: 6,
  },
  {
    id: "b_stripe_payment_failed_dunning",
    section: "billing_client_ops",
    subsection: "stripe",
    label: "payment_failed triggers dunning flow",
    critical: true,
    automatable: true,
    order: 7,
  },
  {
    id: "b_stripe_sub_deleted_churn",
    section: "billing_client_ops",
    subsection: "stripe",
    label: "subscription_deleted logs churn event",
    critical: false,
    automatable: true,
    order: 8,
  },
  {
    id: "b_stripe_test_mode_e2e",
    section: "billing_client_ops",
    subsection: "stripe",
    label: "Full e2e test in Stripe test mode",
    critical: true,
    automatable: true,
    order: 9,
  },

  // ── onboarding ──
  {
    id: "b_onboard_under_5min",
    section: "billing_client_ops",
    subsection: "onboarding",
    label: "Client setup completes in under 5 minutes",
    critical: false,
    automatable: false,
    order: 10,
  },
  {
    id: "b_onboard_config_correct",
    section: "billing_client_ops",
    subsection: "onboarding",
    label: "Configuration stored correctly",
    critical: false,
    automatable: true,
    order: 11,
  },
  {
    id: "b_onboard_dashboard_creds",
    section: "billing_client_ops",
    subsection: "onboarding",
    label: "Dashboard credentials provisioned",
    critical: false,
    automatable: true,
    order: 12,
  },
  {
    id: "b_onboard_welcome_email",
    section: "billing_client_ops",
    subsection: "onboarding",
    label: "Welcome email sent",
    critical: false,
    automatable: true,
    order: 13,
  },
  {
    id: "b_onboard_first_discovery",
    section: "billing_client_ops",
    subsection: "onboarding",
    label: "First discovery batch triggered",
    critical: false,
    automatable: true,
    order: 14,
  },
  {
    id: "b_onboard_telegram_data",
    section: "billing_client_ops",
    subsection: "onboarding",
    label: "Telegram shows client data",
    critical: false,
    automatable: true,
    order: 15,
  },

  // ── client_management ──
  {
    id: "b_client_health_score_daily",
    section: "billing_client_ops",
    subsection: "client_management",
    label: "Health score calculated daily",
    critical: false,
    automatable: true,
    order: 16,
  },
  {
    id: "b_client_alerts_thresholds",
    section: "billing_client_ops",
    subsection: "client_management",
    label: "Alerts fire at health thresholds",
    critical: false,
    automatable: true,
    order: 17,
  },
  {
    id: "b_client_expansion_detection",
    section: "billing_client_ops",
    subsection: "client_management",
    label: "Expansion opportunity detection",
    critical: false,
    automatable: false,
    order: 18,
  },
  {
    id: "b_client_churn_prevention",
    section: "billing_client_ops",
    subsection: "client_management",
    label: "Churn prevention triggers fire",
    critical: false,
    automatable: true,
    order: 19,
  },

  // =======================================================================
  // Section 5 — Reporting & Dashboard
  // =======================================================================

  // ── reports ──
  {
    id: "r_report_weekly_accurate",
    section: "reporting_dashboard",
    subsection: "reports",
    label: "Weekly report data is accurate",
    critical: false,
    automatable: true,
    order: 1,
  },
  {
    id: "r_report_narrative_professional",
    section: "reporting_dashboard",
    subsection: "reports",
    label: "AI narrative is professional and accurate",
    critical: false,
    automatable: false,
    order: 2,
  },
  {
    id: "r_report_email_renders",
    section: "reporting_dashboard",
    subsection: "reports",
    label: "Report email renders correctly",
    critical: false,
    automatable: false,
    order: 3,
  },
  {
    id: "r_report_unsubscribe_works",
    section: "reporting_dashboard",
    subsection: "reports",
    label: "Report unsubscribe link works",
    critical: true,
    automatable: true,
    order: 4,
  },
  {
    id: "r_report_monthly_roi",
    section: "reporting_dashboard",
    subsection: "reports",
    label: "Monthly ROI calculation correct",
    critical: false,
    automatable: true,
    order: 5,
  },
  {
    id: "r_report_daily_digest",
    section: "reporting_dashboard",
    subsection: "reports",
    label: "Daily digest complete and accurate",
    critical: false,
    automatable: true,
    order: 6,
  },

  // ── dashboard ──
  {
    id: "r_dash_login_works",
    section: "reporting_dashboard",
    subsection: "dashboard",
    label: "Login flow works",
    critical: true,
    automatable: true,
    order: 7,
  },
  {
    id: "r_dash_client_isolation",
    section: "reporting_dashboard",
    subsection: "dashboard",
    label: "Client data isolation enforced",
    critical: true,
    automatable: true,
    order: 8,
  },
  {
    id: "r_dash_metrics_correct",
    section: "reporting_dashboard",
    subsection: "dashboard",
    label: "Metrics display correct values",
    critical: false,
    automatable: true,
    order: 9,
  },
  {
    id: "r_dash_pipeline_displays",
    section: "reporting_dashboard",
    subsection: "dashboard",
    label: "Pipeline view displays correctly",
    critical: false,
    automatable: false,
    order: 10,
  },
  {
    id: "r_dash_tables_sort_filter",
    section: "reporting_dashboard",
    subsection: "dashboard",
    label: "Tables support sort, filter, and pagination",
    critical: false,
    automatable: true,
    order: 11,
  },
  {
    id: "r_dash_mobile_responsive",
    section: "reporting_dashboard",
    subsection: "dashboard",
    label: "Mobile responsive layout",
    critical: false,
    automatable: false,
    order: 12,
  },
  {
    id: "r_dash_loading_states",
    section: "reporting_dashboard",
    subsection: "dashboard",
    label: "Loading states shown during data fetch",
    critical: false,
    automatable: false,
    order: 13,
  },
  {
    id: "r_dash_empty_states",
    section: "reporting_dashboard",
    subsection: "dashboard",
    label: "Empty states shown when no data",
    critical: false,
    automatable: false,
    order: 14,
  },
  {
    id: "r_dash_realtime_updates",
    section: "reporting_dashboard",
    subsection: "dashboard",
    label: "Real-time updates work",
    critical: false,
    automatable: true,
    order: 15,
  },
  {
    id: "r_dash_no_console_errors",
    section: "reporting_dashboard",
    subsection: "dashboard",
    label: "No console errors in browser",
    critical: false,
    automatable: true,
    order: 16,
  },
  {
    id: "r_dash_page_load_3s",
    section: "reporting_dashboard",
    subsection: "dashboard",
    label: "Page load under 3 seconds",
    critical: false,
    automatable: true,
    order: 17,
  },
  {
    id: "r_dash_all_links_work",
    section: "reporting_dashboard",
    subsection: "dashboard",
    label: "All links and navigation work",
    critical: false,
    automatable: true,
    order: 18,
  },

  // =======================================================================
  // Section 6 — Acquisition
  // =======================================================================

  {
    id: "a_finds_real_contractors",
    section: "acquisition",
    subsection: "acquisition",
    label: "Finds real contractors in target market",
    critical: false,
    automatable: true,
    order: 1,
  },
  {
    id: "a_scoring_matches_spec",
    section: "acquisition",
    subsection: "acquisition",
    label: "Prospect scoring matches specification",
    critical: false,
    automatable: true,
    order: 2,
  },
  {
    id: "a_emails_pass_compliance",
    section: "acquisition",
    subsection: "acquisition",
    label: "Outreach emails pass compliance checks",
    critical: true,
    automatable: true,
    order: 3,
  },
  {
    id: "a_nurture_sequence_fires",
    section: "acquisition",
    subsection: "acquisition",
    label: "Nurture sequence fires correctly",
    critical: false,
    automatable: true,
    order: 4,
  },
  {
    id: "a_proposal_pdf",
    section: "acquisition",
    subsection: "acquisition",
    label: "Proposal generator outputs PDF",
    critical: false,
    automatable: true,
    order: 5,
  },
  {
    id: "a_paid_discovery_audit_e2e",
    section: "acquisition",
    subsection: "acquisition",
    label: "Paid discovery audit works end-to-end",
    critical: false,
    automatable: true,
    order: 6,
  },
  {
    id: "a_proof_engine_case_study",
    section: "acquisition",
    subsection: "acquisition",
    label: "Proof engine generates case study",
    critical: false,
    automatable: true,
    order: 7,
  },
  {
    id: "a_referral_tracking",
    section: "acquisition",
    subsection: "acquisition",
    label: "Referral tracking records source",
    critical: false,
    automatable: true,
    order: 8,
  },
  {
    id: "a_prospects_command",
    section: "acquisition",
    subsection: "acquisition",
    label: "/prospects Telegram command works",
    critical: false,
    automatable: true,
    order: 9,
  },
  {
    id: "a_proposals_command",
    section: "acquisition",
    subsection: "acquisition",
    label: "/proposals Telegram command works",
    critical: false,
    automatable: true,
    order: 10,
  },

  // =======================================================================
  // Section 7 — Advanced Features
  // =======================================================================

  {
    id: "adv_voice_greeting",
    section: "advanced_features",
    subsection: "advanced",
    label: "Voice receptionist plays greeting",
    critical: false,
    automatable: true,
    order: 1,
  },
  {
    id: "adv_voice_captures_info",
    section: "advanced_features",
    subsection: "advanced",
    label: "Captures caller info from conversation",
    critical: false,
    automatable: false,
    order: 2,
  },
  {
    id: "adv_voice_warm_score",
    section: "advanced_features",
    subsection: "advanced",
    label: "Warm caller scored 60+",
    critical: false,
    automatable: true,
    order: 3,
  },
  {
    id: "adv_voice_call_logged",
    section: "advanced_features",
    subsection: "advanced",
    label: "Calls logged with transcript",
    critical: false,
    automatable: true,
    order: 4,
  },
  {
    id: "adv_review_sms_timing",
    section: "advanced_features",
    subsection: "advanced",
    label: "Review SMS sent with correct timing",
    critical: false,
    automatable: true,
    order: 5,
  },
  {
    id: "adv_review_monitoring",
    section: "advanced_features",
    subsection: "advanced",
    label: "Review monitoring detects new reviews",
    critical: false,
    automatable: true,
    order: 6,
  },
  {
    id: "adv_review_response_drafts",
    section: "advanced_features",
    subsection: "advanced",
    label: "Response drafts are appropriate",
    critical: false,
    automatable: false,
    order: 7,
  },
  {
    id: "adv_funnel_renderer",
    section: "advanced_features",
    subsection: "advanced",
    label: "Funnel renderer produces working page",
    critical: false,
    automatable: true,
    order: 8,
  },
  {
    id: "adv_crm_push_format",
    section: "advanced_features",
    subsection: "advanced",
    label: "CRM push sends correct format",
    critical: false,
    automatable: true,
    order: 9,
  },
  {
    id: "adv_multi_location_routing",
    section: "advanced_features",
    subsection: "advanced",
    label: "Multi-location routing assigns leads correctly",
    critical: false,
    automatable: true,
    order: 10,
  },

  // =======================================================================
  // Section 8 — Full System Audit
  // =======================================================================

  // ── e2e_pipeline ──
  {
    id: "fs_e2e_create_test_client",
    section: "full_system",
    subsection: "e2e_pipeline",
    label: "Create test client",
    critical: false,
    automatable: true,
    order: 1,
  },
  {
    id: "fs_e2e_run_discovery",
    section: "full_system",
    subsection: "e2e_pipeline",
    label: "Run discovery for test client",
    critical: false,
    automatable: true,
    order: 2,
  },
  {
    id: "fs_e2e_run_enrichment",
    section: "full_system",
    subsection: "e2e_pipeline",
    label: "Run enrichment on discovered leads",
    critical: false,
    automatable: true,
    order: 3,
  },
  {
    id: "fs_e2e_run_scoring",
    section: "full_system",
    subsection: "e2e_pipeline",
    label: "Run scoring on enriched leads",
    critical: false,
    automatable: true,
    order: 4,
  },
  {
    id: "fs_e2e_run_outreach_dry",
    section: "full_system",
    subsection: "e2e_pipeline",
    label: "Run outreach in dry-run mode",
    critical: false,
    automatable: true,
    order: 5,
  },
  {
    id: "fs_e2e_simulate_reply",
    section: "full_system",
    subsection: "e2e_pipeline",
    label: "Simulate lead reply",
    critical: false,
    automatable: true,
    order: 6,
  },
  {
    id: "fs_e2e_simulate_conversion",
    section: "full_system",
    subsection: "e2e_pipeline",
    label: "Simulate conversion event",
    critical: false,
    automatable: true,
    order: 7,
  },
  {
    id: "fs_e2e_generate_report",
    section: "full_system",
    subsection: "e2e_pipeline",
    label: "Generate report for test client",
    critical: false,
    automatable: true,
    order: 8,
  },
  {
    id: "fs_e2e_check_stripe",
    section: "full_system",
    subsection: "e2e_pipeline",
    label: "Verify Stripe records correct",
    critical: false,
    automatable: true,
    order: 9,
  },
  {
    id: "fs_e2e_check_dashboard",
    section: "full_system",
    subsection: "e2e_pipeline",
    label: "Verify dashboard shows test data",
    critical: false,
    automatable: false,
    order: 10,
  },
  {
    id: "fs_e2e_check_telegram",
    section: "full_system",
    subsection: "e2e_pipeline",
    label: "Verify Telegram received alerts",
    critical: false,
    automatable: true,
    order: 11,
  },
  {
    id: "fs_e2e_check_health",
    section: "full_system",
    subsection: "e2e_pipeline",
    label: "Verify /health still green",
    critical: false,
    automatable: true,
    order: 12,
  },

  // ── failure_modes ──
  {
    id: "fs_fail_kill_claude",
    section: "full_system",
    subsection: "failure_modes",
    label: "System handles Claude API outage",
    critical: false,
    automatable: true,
    order: 13,
  },
  {
    id: "fs_fail_kill_supabase",
    section: "full_system",
    subsection: "failure_modes",
    label: "System handles Supabase outage",
    critical: false,
    automatable: true,
    order: 14,
  },
  {
    id: "fs_fail_kill_stripe",
    section: "full_system",
    subsection: "failure_modes",
    label: "System handles Stripe outage",
    critical: false,
    automatable: true,
    order: 15,
  },
  {
    id: "fs_fail_kill_twilio",
    section: "full_system",
    subsection: "failure_modes",
    label: "System handles Twilio outage",
    critical: false,
    automatable: true,
    order: 16,
  },
  {
    id: "fs_fail_kill_smtp",
    section: "full_system",
    subsection: "failure_modes",
    label: "System handles SMTP outage",
    critical: false,
    automatable: true,
    order: 17,
  },
  {
    id: "fs_fail_load_test",
    section: "full_system",
    subsection: "failure_modes",
    label: "Handles 1000 req/s load test",
    critical: false,
    automatable: true,
    order: 18,
  },
  {
    id: "fs_fail_xss_payload",
    section: "full_system",
    subsection: "failure_modes",
    label: "XSS payload rejected",
    critical: true,
    automatable: true,
    order: 19,
  },
  {
    id: "fs_fail_sql_injection",
    section: "full_system",
    subsection: "failure_modes",
    label: "SQL injection attempt blocked",
    critical: true,
    automatable: true,
    order: 20,
  },
  {
    id: "fs_fail_invalid_webhook_sig",
    section: "full_system",
    subsection: "failure_modes",
    label: "Invalid webhook signature rejected",
    critical: true,
    automatable: true,
    order: 21,
  },
  {
    id: "fs_fail_exceed_budget",
    section: "full_system",
    subsection: "failure_modes",
    label: "Budget cap exceeded triggers shutdown",
    critical: true,
    automatable: true,
    order: 22,
  },

  // ── performance ──
  {
    id: "fs_perf_api_read_200ms",
    section: "full_system",
    subsection: "performance",
    label: "API read responses under 200ms",
    critical: false,
    automatable: true,
    order: 23,
  },
  {
    id: "fs_perf_api_write_500ms",
    section: "full_system",
    subsection: "performance",
    label: "API write responses under 500ms",
    critical: false,
    automatable: true,
    order: 24,
  },
  {
    id: "fs_perf_dashboard_3s",
    section: "full_system",
    subsection: "performance",
    label: "Dashboard loads under 3 seconds",
    critical: false,
    automatable: true,
    order: 25,
  },
  {
    id: "fs_perf_claude_5s",
    section: "full_system",
    subsection: "performance",
    label: "Claude responses under 5 seconds",
    critical: false,
    automatable: true,
    order: 26,
  },
  {
    id: "fs_perf_db_queries_100ms",
    section: "full_system",
    subsection: "performance",
    label: "Database queries under 100ms",
    critical: false,
    automatable: true,
    order: 27,
  },
  {
    id: "fs_perf_scheduled_jobs_on_time",
    section: "full_system",
    subsection: "performance",
    label: "Scheduled jobs fire on time",
    critical: false,
    automatable: true,
    order: 28,
  },
  {
    id: "fs_perf_telegram_3s",
    section: "full_system",
    subsection: "performance",
    label: "Telegram delivery under 3 seconds",
    critical: false,
    automatable: true,
    order: 29,
  },
  {
    id: "fs_perf_email_2s",
    section: "full_system",
    subsection: "performance",
    label: "Email send under 2 seconds",
    critical: false,
    automatable: true,
    order: 30,
  },
  {
    id: "fs_perf_sms_1s",
    section: "full_system",
    subsection: "performance",
    label: "SMS send under 1 second",
    critical: false,
    automatable: true,
    order: 31,
  },
  {
    id: "fs_perf_memory_stable_24h",
    section: "full_system",
    subsection: "performance",
    label: "Memory usage stable over 24 hours",
    critical: false,
    automatable: true,
    order: 32,
  },
  {
    id: "fs_perf_cpu_under_50",
    section: "full_system",
    subsection: "performance",
    label: "CPU under 50% at peak load",
    critical: false,
    automatable: true,
    order: 33,
  },

  // =======================================================================
  // Section 9 — Pre-Onboard Check
  // =======================================================================

  {
    id: "po_service_area_sources",
    section: "pre_onboard",
    subsection: "pre_onboard",
    label: "Service area has discovery sources configured",
    critical: false,
    automatable: true,
    order: 1,
  },
  {
    id: "po_vertical_templates",
    section: "pre_onboard",
    subsection: "pre_onboard",
    label: "Vertical has outreach templates",
    critical: false,
    automatable: true,
    order: 2,
  },
  {
    id: "po_email_warmup_2w",
    section: "pre_onboard",
    subsection: "pre_onboard",
    label: "Email warmup at least 2 weeks old",
    critical: true,
    automatable: true,
    order: 3,
  },
  {
    id: "po_sms_number_warmed",
    section: "pre_onboard",
    subsection: "pre_onboard",
    label: "SMS number warmed up",
    critical: false,
    automatable: true,
    order: 4,
  },
  {
    id: "po_stripe_active",
    section: "pre_onboard",
    subsection: "pre_onboard",
    label: "Stripe subscription active",
    critical: true,
    automatable: true,
    order: 5,
  },
  {
    id: "po_dashboard_creds",
    section: "pre_onboard",
    subsection: "pre_onboard",
    label: "Dashboard credentials provisioned",
    critical: false,
    automatable: true,
    order: 6,
  },
  {
    id: "po_branding_uploaded",
    section: "pre_onboard",
    subsection: "pre_onboard",
    label: "Client branding assets uploaded",
    critical: false,
    automatable: true,
    order: 7,
  },
  {
    id: "po_discovery_dry_run",
    section: "pre_onboard",
    subsection: "pre_onboard",
    label: "Discovery dry-run produces leads",
    critical: false,
    automatable: true,
    order: 8,
  },
  {
    id: "po_outreach_dry_run",
    section: "pre_onboard",
    subsection: "pre_onboard",
    label: "Outreach dry-run passes compliance",
    critical: true,
    automatable: true,
    order: 9,
  },
  {
    id: "po_client_command",
    section: "pre_onboard",
    subsection: "pre_onboard",
    label: "/client Telegram command works for this client",
    critical: false,
    automatable: true,
    order: 10,
  },
  {
    id: "po_report_generation",
    section: "pre_onboard",
    subsection: "pre_onboard",
    label: "Report generation works for this client",
    critical: false,
    automatable: true,
    order: 11,
  },
  {
    id: "po_budget_caps",
    section: "pre_onboard",
    subsection: "pre_onboard",
    label: "Budget caps configured for client",
    critical: true,
    automatable: true,
    order: 12,
  },
  {
    id: "po_approval_queue",
    section: "pre_onboard",
    subsection: "pre_onboard",
    label: "Approval queue working for client",
    critical: false,
    automatable: true,
    order: 13,
  },

  // =======================================================================
  // Section 10 — Monthly Health & Drift Check
  // =======================================================================

  // ── code_quality ──
  {
    id: "mh_cq_type_hints",
    section: "monthly_health",
    subsection: "code_quality",
    label: "Type hints on all public functions",
    critical: false,
    automatable: true,
    order: 1,
  },
  {
    id: "mh_cq_docstrings",
    section: "monthly_health",
    subsection: "code_quality",
    label: "Docstrings on all modules and public functions",
    critical: false,
    automatable: true,
    order: 2,
  },
  {
    id: "mh_cq_no_todo_without_ticket",
    section: "monthly_health",
    subsection: "code_quality",
    label: "No TODO without associated ticket",
    critical: false,
    automatable: true,
    order: 3,
  },
  {
    id: "mh_cq_test_coverage_stable",
    section: "monthly_health",
    subsection: "code_quality",
    label: "Test coverage stable or improving",
    critical: false,
    automatable: true,
    order: 4,
  },
  {
    id: "mh_cq_no_deprecated_deps",
    section: "monthly_health",
    subsection: "code_quality",
    label: "No deprecated dependencies",
    critical: false,
    automatable: true,
    order: 5,
  },

  // ── data_quality ──
  {
    id: "mh_dq_scoring_distribution",
    section: "monthly_health",
    subsection: "data_quality",
    label: "Scoring distribution is reasonable",
    critical: false,
    automatable: true,
    order: 6,
  },
  {
    id: "mh_dq_enrichment_rate",
    section: "monthly_health",
    subsection: "data_quality",
    label: "Enrichment rate stable",
    critical: false,
    automatable: true,
    order: 7,
  },
  {
    id: "mh_dq_email_deliverability",
    section: "monthly_health",
    subsection: "data_quality",
    label: "Email deliverability rate stable",
    critical: false,
    automatable: true,
    order: 8,
  },
  {
    id: "mh_dq_sms_delivery",
    section: "monthly_health",
    subsection: "data_quality",
    label: "SMS delivery rate stable",
    critical: false,
    automatable: true,
    order: 9,
  },
  {
    id: "mh_dq_no_zero_leads_7d",
    section: "monthly_health",
    subsection: "data_quality",
    label: "No clients with 0 leads for 7+ days",
    critical: false,
    automatable: true,
    order: 10,
  },

  // ── cost_tracking ──
  {
    id: "mh_cost_per_client_range",
    section: "monthly_health",
    subsection: "cost_tracking",
    label: "Per-client costs within expected range",
    critical: false,
    automatable: true,
    order: 11,
  },
  {
    id: "mh_cost_no_runaway",
    section: "monthly_health",
    subsection: "cost_tracking",
    label: "No runaway cost spikes",
    critical: false,
    automatable: true,
    order: 12,
  },
  {
    id: "mh_cost_claude_proportional",
    section: "monthly_health",
    subsection: "cost_tracking",
    label: "Claude usage proportional to client count",
    critical: false,
    automatable: true,
    order: 13,
  },
  {
    id: "mh_cost_twilio_matches",
    section: "monthly_health",
    subsection: "cost_tracking",
    label: "Twilio spend matches message volume",
    critical: false,
    automatable: true,
    order: 14,
  },

  // ── security ──
  {
    id: "mh_sec_full_audit",
    section: "monthly_health",
    subsection: "security",
    label: "Full security audit completed",
    critical: true,
    automatable: false,
    order: 15,
  },
  {
    id: "mh_sec_keys_rotated",
    section: "monthly_health",
    subsection: "security",
    label: "API keys rotated on schedule",
    critical: true,
    automatable: true,
    order: 16,
  },
  {
    id: "mh_sec_no_secrets_in_code",
    section: "monthly_health",
    subsection: "security",
    label: "No secrets in source code",
    critical: true,
    automatable: true,
    order: 17,
  },
  {
    id: "mh_sec_deps_scanned",
    section: "monthly_health",
    subsection: "security",
    label: "Dependencies scanned for vulnerabilities",
    critical: true,
    automatable: true,
    order: 18,
  },
  {
    id: "mh_sec_logs_reviewed",
    section: "monthly_health",
    subsection: "security",
    label: "Security logs reviewed",
    critical: true,
    automatable: false,
    order: 19,
  },

  // ── compliance ──
  {
    id: "mh_comp_unsubscribe_working",
    section: "monthly_health",
    subsection: "compliance",
    label: "Unsubscribe flow still working",
    critical: true,
    automatable: true,
    order: 20,
  },
  {
    id: "mh_comp_dnc_functioning",
    section: "monthly_health",
    subsection: "compliance",
    label: "DNC list functioning",
    critical: true,
    automatable: true,
    order: 21,
  },
  {
    id: "mh_comp_time_of_day",
    section: "monthly_health",
    subsection: "compliance",
    label: "Time-of-day restrictions correct",
    critical: true,
    automatable: true,
    order: 22,
  },
  {
    id: "mh_comp_optout_matches_suppression",
    section: "monthly_health",
    subsection: "compliance",
    label: "Opt-out count matches suppression list",
    critical: true,
    automatable: true,
    order: 23,
  },
  {
    id: "mh_comp_audit_trail",
    section: "monthly_health",
    subsection: "compliance",
    label: "Audit trail complete and unbroken",
    critical: true,
    automatable: true,
    order: 24,
  },

  // ── performance ──
  {
    id: "mh_perf_api_baseline",
    section: "monthly_health",
    subsection: "performance",
    label: "API response times within baseline",
    critical: false,
    automatable: true,
    order: 25,
  },
  {
    id: "mh_perf_db_baseline",
    section: "monthly_health",
    subsection: "performance",
    label: "Database query times within baseline",
    critical: false,
    automatable: true,
    order: 26,
  },
  {
    id: "mh_perf_no_memory_leaks",
    section: "monthly_health",
    subsection: "performance",
    label: "No memory leaks detected",
    critical: false,
    automatable: true,
    order: 27,
  },
  {
    id: "mh_perf_scheduled_on_time",
    section: "monthly_health",
    subsection: "performance",
    label: "Scheduled jobs firing on time",
    critical: false,
    automatable: true,
    order: 28,
  },
  {
    id: "mh_perf_error_rate_normal",
    section: "monthly_health",
    subsection: "performance",
    label: "Error rate within normal range",
    critical: false,
    automatable: true,
    order: 29,
  },
];

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

/** Return all checks belonging to a given section. */
export function getChecksBySection(section: QaSection): QaCheck[] {
  return QA_CHECKS.filter((c) => c.section === section);
}

/** Return every check marked as critical. */
export function getCriticalChecks(): QaCheck[] {
  return QA_CHECKS.filter((c) => c.critical);
}

/** Return every check that can be verified programmatically. */
export function getAutomatableChecks(): QaCheck[] {
  return QA_CHECKS.filter((c) => c.automatable);
}

/** Look up section metadata by section key. */
export function getSectionMeta(section: QaSection): QaSectionMeta | undefined {
  return QA_SECTIONS.find((s) => s.section === section);
}

/** Return aggregate counts across the entire checklist. */
export function getCheckCount(): {
  total: number;
  critical: number;
  automatable: number;
} {
  return {
    total: QA_CHECKS.length,
    critical: QA_CHECKS.filter((c) => c.critical).length,
    automatable: QA_CHECKS.filter((c) => c.automatable).length,
  };
}
