import type { Metadata } from "next";
import {
  LegalPageLayout,
  type LegalSection,
} from "@/components/legal/LegalPageLayout";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "Sovereign AI privacy policy — how we collect, use, and protect your data.",
  alternates: { canonical: "/legal/privacy" },
  openGraph: {
    title: "Privacy Policy | Sovereign AI",
    description:
      "Sovereign AI privacy policy — how we collect, use, and protect your data.",
    url: "/legal/privacy",
  },
  twitter: {
    card: "summary_large_image",
    title: "Privacy Policy | Sovereign AI",
    description:
      "Sovereign AI privacy policy — how we collect, use, and protect your data.",
  },
};

const sections: readonly LegalSection[] = [
  {
    id: "information-collected",
    number: 1,
    title: "Information We Collect",
    content: (
      <>
        <p>
          When you use Sovereign AI, we collect information you provide
          directly:
        </p>
        <ul className="mt-2 list-disc space-y-1 pl-5">
          <li>
            <strong className="text-foreground">Account Information:</strong>{" "}
            Name, email address, phone number, business name, and address
            provided during onboarding.
          </li>
          <li>
            <strong className="text-foreground">Business Data:</strong>{" "}
            Industry vertical, service area, marketing budget, competitors, and
            other business details shared during setup.
          </li>
          <li>
            <strong className="text-foreground">Payment Information:</strong>{" "}
            Processed securely by Stripe. We do not store credit card numbers.
          </li>
          <li>
            <strong className="text-foreground">Service Data:</strong> Content
            generated by our AI services, chatbot conversations, review
            campaign data, email campaigns, and booking information.
          </li>
          <li>
            <strong className="text-foreground">Usage Data:</strong> Pages
            visited, features used, and interactions with our dashboard.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "how-we-use",
    number: 2,
    title: "How We Use Your Information",
    content: (
      <ul className="list-disc space-y-1 pl-5">
        <li>
          Provide, maintain, and improve our AI marketing services
        </li>
        <li>
          Generate AI-powered content, chatbot responses, and marketing
          materials for your business
        </li>
        <li>Process payments and manage your subscription</li>
        <li>
          Send transactional emails (magic links, service notifications,
          billing alerts)
        </li>
        <li>
          Analyze service performance and generate your dashboard metrics
        </li>
        <li>Provide customer support</li>
      </ul>
    ),
  },
  {
    id: "third-party",
    number: 3,
    title: "Third-Party Services",
    content: (
      <>
        <p>
          We use the following third-party services to deliver our platform:
        </p>
        <ul className="mt-2 list-disc space-y-1 pl-5">
          <li>
            <strong className="text-foreground">Stripe:</strong> Payment
            processing. Stripe&apos;s privacy policy applies to payment data.
          </li>
          <li>
            <strong className="text-foreground">
              Anthropic (Claude AI):
            </strong>{" "}
            Powers our AI chatbot and content generation services. Business
            context is sent to generate responses.
          </li>
          <li>
            <strong className="text-foreground">SendGrid:</strong> Email
            delivery for magic links, notifications, and email marketing
            campaigns.
          </li>
          <li>
            <strong className="text-foreground">Vercel:</strong> Application
            hosting and infrastructure.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "data-retention",
    number: 4,
    title: "Data Retention",
    content: (
      <p>
        We retain your data for as long as your account is active. Upon
        cancellation, we retain data for 90 days to allow for reactivation,
        after which it is permanently deleted. You may request immediate
        deletion at any time by contacting us.
      </p>
    ),
  },
  {
    id: "client-data",
    number: 5,
    title: "Client Customer Data",
    content: (
      <p>
        As a SaaS platform, we process data about your customers
        (&ldquo;End-User Data&rdquo;) on your behalf, including lead names,
        email addresses, phone numbers, and booking information. We act as a
        data processor for this information. You remain the data controller and
        are responsible for obtaining appropriate consent from your customers.
        We process End-User Data solely to provide the services you have
        requested and do not sell, share, or use it for our own marketing
        purposes.
      </p>
    ),
  },
  {
    id: "data-security",
    number: 6,
    title: "Data Security",
    content: (
      <p>
        We implement industry-standard security measures including encrypted
        data transmission (TLS), AES-256-GCM encryption at rest for
        high-sensitivity PII fields (phone numbers, email addresses, and
        physical addresses), secure session management, and role-based access
        controls. Payment information is handled exclusively by Stripe&apos;s
        PCI-compliant infrastructure.
      </p>
    ),
  },
  {
    id: "gdpr",
    number: 7,
    title: "Your Rights (GDPR)",
    content: (
      <>
        <p>
          If you are in the European Economic Area, United Kingdom, or a
          jurisdiction with similar data protection laws, you have the right to:
        </p>
        <ul className="mt-2 list-disc space-y-1 pl-5">
          <li>
            <strong className="text-foreground">Access:</strong> Request a copy
            of the personal data we hold about you via Dashboard &gt; Settings
            &gt; Export Data, or by contacting us.
          </li>
          <li>
            <strong className="text-foreground">Rectification:</strong> Request
            correction of inaccurate data.
          </li>
          <li>
            <strong className="text-foreground">Erasure:</strong> Request
            deletion of your data via Dashboard &gt; Settings &gt; Delete
            Account, or by contacting us.
          </li>
          <li>
            <strong className="text-foreground">Data Portability:</strong>{" "}
            Export your data in a machine-readable JSON format.
          </li>
          <li>
            <strong className="text-foreground">Restriction:</strong> Request
            that we restrict processing of your data.
          </li>
          <li>
            <strong className="text-foreground">Objection:</strong> Object to
            processing based on legitimate interests.
          </li>
          <li>
            <strong className="text-foreground">Withdraw Consent:</strong>{" "}
            Withdraw consent at any time where processing is based on consent
            (e.g., analytics cookies).
          </li>
        </ul>
        <p className="mt-2">
          You can export all your personal data from your account settings at
          any time by navigating to Dashboard &gt; Settings &gt; Privacy &amp;
          Data and clicking &ldquo;Download My Data.&rdquo; Your data will be
          provided in a portable, machine-readable JSON format.
        </p>
        <p className="mt-2">
          We will respond to all data subject requests within 30 days.
        </p>
      </>
    ),
  },
  {
    id: "ccpa",
    number: 8,
    title: "California Privacy Rights (CCPA/CPRA)",
    content: (
      <>
        <p>
          If you are a California resident, you have additional rights under the
          California Consumer Privacy Act:
        </p>
        <ul className="mt-2 list-disc space-y-1 pl-5">
          <li>
            <strong className="text-foreground">Right to Know:</strong> You may
            request disclosure of the categories and specific pieces of personal
            information we have collected about you.
          </li>
          <li>
            <strong className="text-foreground">Right to Delete:</strong> You
            may request deletion of your personal information, subject to
            certain exceptions.
          </li>
          <li>
            <strong className="text-foreground">
              Right to Opt Out of Sale:
            </strong>{" "}
            We do not sell personal information. We do not share personal
            information for cross-context behavioral advertising.
          </li>
          <li>
            <strong className="text-foreground">
              Right to Non-Discrimination:
            </strong>{" "}
            We will not discriminate against you for exercising your privacy
            rights.
          </li>
        </ul>
        <p className="mt-2">
          To exercise these rights, contact us at{" "}
          <a
            href="mailto:privacy@trysovereignai.com"
            className="text-primary underline decoration-primary/30 underline-offset-2 hover:decoration-primary"
          >
            privacy@trysovereignai.com
          </a>{" "}
          or use the data deletion feature in your dashboard.
        </p>
      </>
    ),
  },
  {
    id: "cookies",
    number: 9,
    title: "Cookies and Analytics",
    content: (
      <>
        <p>We use the following categories of cookies:</p>
        <ul className="mt-2 list-disc space-y-1 pl-5">
          <li>
            <strong className="text-foreground">Essential Cookies:</strong>{" "}
            Required for authentication and session management. These cannot be
            disabled.
          </li>
          <li>
            <strong className="text-foreground">
              Analytics Cookies (optional):
            </strong>{" "}
            Google Analytics (GA4) to understand site usage and improve our
            services. Only loaded after you consent via our cookie banner.
          </li>
          <li>
            <strong className="text-foreground">
              Advertising Cookies (optional):
            </strong>{" "}
            Facebook Pixel to measure advertising effectiveness. Only loaded
            after you consent via our cookie banner.
          </li>
        </ul>
        <p className="mt-2">
          You can withdraw cookie consent at any time by clearing your
          browser&apos;s local storage for our domain. Analytics and advertising
          scripts are not loaded until you explicitly accept cookies. For more
          details, see our{" "}
          <a
            href="/legal/cookies"
            className="text-primary underline decoration-primary/30 underline-offset-2 hover:decoration-primary"
          >
            Cookie Policy
          </a>
          .
        </p>
      </>
    ),
  },
  {
    id: "children",
    number: 10,
    title: "Children's Privacy",
    content: (
      <p>
        Our services are not directed at individuals under 18 years of age. We
        do not knowingly collect personal information from children. If we learn
        that we have collected personal data from a child, we will delete it
        promptly.
      </p>
    ),
  },
  {
    id: "international",
    number: 11,
    title: "International Data Transfers",
    content: (
      <p>
        Your data may be processed in the United States by our hosting provider
        (Vercel) and sub-processors. By using our services, you consent to this
        transfer. We ensure appropriate safeguards are in place for any
        international data transfers.
      </p>
    ),
  },
  {
    id: "changes",
    number: 12,
    title: "Changes to This Policy",
    content: (
      <p>
        We may update this privacy policy from time to time. We will notify you
        of material changes via email. The &ldquo;Last updated&rdquo; date at
        the top of this page indicates the most recent revision.
      </p>
    ),
  },
  {
    id: "contact",
    number: 13,
    title: "Contact Us",
    content: (
      <p>
        For privacy-related inquiries, data subject requests, or complaints,
        contact us at{" "}
        <a
          href="mailto:privacy@trysovereignai.com"
          className="text-primary underline decoration-primary/30 underline-offset-2 hover:decoration-primary"
        >
          privacy@trysovereignai.com
        </a>
        .
      </p>
    ),
  },
];

export default function PrivacyPage() {
  return (
    <LegalPageLayout
      title="Privacy Policy"
      lastUpdated="March 28, 2026"
      sections={sections}
    />
  );
}
