import type { Metadata } from "next";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { Container } from "@/components/layout/Container";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Sovereign AI privacy policy — how we collect, use, and protect your data.",
};

export default function PrivacyPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <Header />
      <main className="flex-1 py-16">
        <Container>
          <div className="mx-auto max-w-3xl">
            <h1 className="text-3xl font-bold">Privacy Policy</h1>
            <p className="mt-2 text-sm text-muted-foreground">Last updated: March 2026</p>

            <div className="mt-10 space-y-8 text-sm leading-relaxed text-muted-foreground">
              <section>
                <h2 className="mb-3 text-lg font-semibold text-foreground">1. Information We Collect</h2>
                <p>When you use Sovereign AI, we collect information you provide directly:</p>
                <ul className="mt-2 list-disc space-y-1 pl-5">
                  <li><strong className="text-foreground">Account Information:</strong> Name, email address, phone number, business name, and address provided during onboarding.</li>
                  <li><strong className="text-foreground">Business Data:</strong> Industry vertical, service area, marketing budget, competitors, and other business details shared during setup.</li>
                  <li><strong className="text-foreground">Payment Information:</strong> Processed securely by Stripe. We do not store credit card numbers.</li>
                  <li><strong className="text-foreground">Service Data:</strong> Content generated by our AI services, chatbot conversations, review campaign data, email campaigns, and booking information.</li>
                  <li><strong className="text-foreground">Usage Data:</strong> Pages visited, features used, and interactions with our dashboard.</li>
                </ul>
              </section>

              <section>
                <h2 className="mb-3 text-lg font-semibold text-foreground">2. How We Use Your Information</h2>
                <ul className="list-disc space-y-1 pl-5">
                  <li>Provide, maintain, and improve our AI marketing services</li>
                  <li>Generate AI-powered content, chatbot responses, and marketing materials for your business</li>
                  <li>Process payments and manage your subscription</li>
                  <li>Send transactional emails (magic links, service notifications, billing alerts)</li>
                  <li>Analyze service performance and generate your dashboard metrics</li>
                  <li>Provide customer support</li>
                </ul>
              </section>

              <section>
                <h2 className="mb-3 text-lg font-semibold text-foreground">3. Third-Party Services</h2>
                <p>We use the following third-party services to deliver our platform:</p>
                <ul className="mt-2 list-disc space-y-1 pl-5">
                  <li><strong className="text-foreground">Stripe:</strong> Payment processing. Stripe&apos;s privacy policy applies to payment data.</li>
                  <li><strong className="text-foreground">Anthropic (Claude AI):</strong> Powers our AI chatbot and content generation services. Business context is sent to generate responses.</li>
                  <li><strong className="text-foreground">SendGrid:</strong> Email delivery for magic links, notifications, and email marketing campaigns.</li>
                  <li><strong className="text-foreground">Vercel:</strong> Application hosting and infrastructure.</li>
                </ul>
              </section>

              <section>
                <h2 className="mb-3 text-lg font-semibold text-foreground">4. Data Retention</h2>
                <p>We retain your data for as long as your account is active. Upon cancellation, we retain data for 90 days to allow for reactivation, after which it is permanently deleted. You may request immediate deletion at any time by contacting us.</p>
              </section>

              <section>
                <h2 className="mb-3 text-lg font-semibold text-foreground">5. Data Security</h2>
                <p>We implement industry-standard security measures including encrypted data transmission (TLS), secure session management, and access controls. Payment information is handled exclusively by Stripe&apos;s PCI-compliant infrastructure.</p>
              </section>

              <section>
                <h2 className="mb-3 text-lg font-semibold text-foreground">6. Your Rights</h2>
                <p>You have the right to:</p>
                <ul className="mt-2 list-disc space-y-1 pl-5">
                  <li>Access the personal data we hold about you</li>
                  <li>Request correction of inaccurate data</li>
                  <li>Request deletion of your data</li>
                  <li>Export your data in a portable format</li>
                  <li>Opt out of marketing communications</li>
                </ul>
              </section>

              <section>
                <h2 className="mb-3 text-lg font-semibold text-foreground">7. Cookies</h2>
                <p>We use essential cookies for authentication (session cookies). We do not use third-party tracking cookies or advertising cookies.</p>
              </section>

              <section>
                <h2 className="mb-3 text-lg font-semibold text-foreground">8. Contact Us</h2>
                <p>For privacy-related inquiries, contact us at <a href="mailto:privacy@sovereignai.com" className="text-primary hover:underline">privacy@sovereignai.com</a>.</p>
              </section>
            </div>
          </div>
        </Container>
      </main>
      <Footer />
    </div>
  );
}
