import type { Metadata } from "next";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { Container } from "@/components/layout/Container";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Sovereign AI terms of service — the agreement governing use of our platform.",
};

export default function TermsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background">
      <Header />
      <main className="flex-1 py-16">
        <Container>
          <div className="mx-auto max-w-3xl">
            <h1 className="text-3xl font-bold">Terms of Service</h1>
            <p className="mt-2 text-sm text-muted-foreground">Last updated: March 2026</p>

            <div className="mt-10 space-y-8 text-sm leading-relaxed text-muted-foreground">
              <section>
                <h2 className="mb-3 text-lg font-semibold text-foreground">1. Agreement</h2>
                <p>By accessing or using Sovereign AI (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you are using the Service on behalf of a business, you represent that you have authority to bind that business to these terms.</p>
              </section>

              <section>
                <h2 className="mb-3 text-lg font-semibold text-foreground">2. Services</h2>
                <p>Sovereign AI provides AI-powered marketing automation services for local businesses, including but not limited to: AI chatbots, content generation, review management, email marketing, SEO, advertising management, and lead generation. Services are delivered as described in your selected plan or bundle.</p>
              </section>

              <section>
                <h2 className="mb-3 text-lg font-semibold text-foreground">3. Billing & Payment</h2>
                <ul className="list-disc space-y-1 pl-5">
                  <li>Subscriptions are billed monthly via Stripe. Prices are as listed at the time of purchase.</li>
                  <li>Your subscription renews automatically each month unless canceled.</li>
                  <li>You may cancel at any time. Cancellation takes effect at the end of your current billing period.</li>
                  <li>We offer a 30-day money-back guarantee for new subscribers. Contact support within 30 days of your first payment for a full refund.</li>
                  <li>Failed payments may result in service suspension after a 7-day grace period.</li>
                </ul>
              </section>

              <section>
                <h2 className="mb-3 text-lg font-semibold text-foreground">4. AI-Generated Content</h2>
                <p>Content generated by our AI services (blog posts, social media posts, email copy, chatbot responses) is created for your business&apos;s use. You own the rights to all content generated for your account. We do not guarantee that AI-generated content will be error-free and recommend reviewing content before publication.</p>
              </section>

              <section>
                <h2 className="mb-3 text-lg font-semibold text-foreground">5. Your Responsibilities</h2>
                <ul className="list-disc space-y-1 pl-5">
                  <li>Provide accurate business information during onboarding</li>
                  <li>Maintain the security of your account credentials</li>
                  <li>Review AI-generated content for accuracy before publication</li>
                  <li>Comply with all applicable laws regarding marketing, advertising, and data privacy</li>
                  <li>Not use the Service for any unlawful purpose</li>
                </ul>
              </section>

              <section>
                <h2 className="mb-3 text-lg font-semibold text-foreground">6. Service Level</h2>
                <p>We strive for 99.9% uptime for our platform. AI services are deployed within 48 hours of onboarding completion. We do not guarantee specific results (lead counts, revenue increases) as outcomes depend on many factors beyond our control.</p>
              </section>

              <section>
                <h2 className="mb-3 text-lg font-semibold text-foreground">7. Limitation of Liability</h2>
                <p>To the maximum extent permitted by law, Sovereign AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the Service. Our total liability shall not exceed the amount paid by you in the 12 months preceding the claim.</p>
              </section>

              <section>
                <h2 className="mb-3 text-lg font-semibold text-foreground">8. Termination</h2>
                <p>Either party may terminate this agreement at any time. Upon termination, your access to the Service will end at the conclusion of your current billing period. We will retain your data for 90 days post-termination.</p>
              </section>

              <section>
                <h2 className="mb-3 text-lg font-semibold text-foreground">9. Changes to Terms</h2>
                <p>We may update these terms from time to time. We will notify you of material changes via email. Continued use of the Service after changes constitutes acceptance of the updated terms.</p>
              </section>

              <section>
                <h2 className="mb-3 text-lg font-semibold text-foreground">10. Contact</h2>
                <p>For questions about these terms, contact us at <a href="mailto:legal@sovereignai.com" className="text-primary hover:underline">legal@sovereignai.com</a>.</p>
              </section>
            </div>
          </div>
        </Container>
      </main>
      <Footer />
    </div>
  );
}
