import type { Metadata } from "next";
import {
  LegalPageLayout,
  type LegalSection,
} from "@/components/legal/LegalPageLayout";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Sovereign AI terms of service — the agreement governing use of our platform.",
  alternates: { canonical: "/legal/terms" },
  openGraph: {
    title: "Terms of Service | Sovereign AI",
    description:
      "Sovereign AI terms of service — the agreement governing use of our platform.",
    url: "/legal/terms",
  },
  twitter: {
    card: "summary_large_image",
    title: "Terms of Service | Sovereign AI",
    description:
      "Sovereign AI terms of service — the agreement governing use of our platform.",
  },
};

const sections: readonly LegalSection[] = [
  {
    id: "agreement",
    number: 1,
    title: "Agreement",
    content: (
      <p>
        By accessing or using Sovereign AI (&ldquo;the Service&rdquo;), you
        agree to be bound by these Terms of Service. If you are using the
        Service on behalf of a business, you represent that you have authority
        to bind that business to these terms.
      </p>
    ),
  },
  {
    id: "services",
    number: 2,
    title: "Services",
    content: (
      <p>
        Sovereign AI provides AI-powered marketing automation services for
        local businesses, including but not limited to: AI chatbots, content
        generation, review management, email marketing, SEO, advertising
        management, and lead generation. Services are delivered as described in
        your selected plan or bundle.
      </p>
    ),
  },
  {
    id: "billing",
    number: 3,
    title: "Billing & Payment",
    content: (
      <ul className="list-disc space-y-1 pl-5">
        <li>
          Subscriptions are billed monthly via Stripe. Prices are as listed at
          the time of purchase.
        </li>
        <li>
          Your subscription renews automatically each month unless canceled.
        </li>
        <li>
          You may cancel at any time. Cancellation takes effect at the end of
          your current billing period.
        </li>
        <li>
          We offer a 60-day money-back guarantee for new subscribers. Contact
          support within 60 days of your first payment for a full refund.
        </li>
        <li>
          Failed payments may result in service suspension after a 7-day grace
          period.
        </li>
      </ul>
    ),
  },
  {
    id: "ai-content",
    number: 4,
    title: "AI-Generated Content",
    content: (
      <p>
        Content generated by our AI services (blog posts, social media posts,
        email copy, chatbot responses) is created for your business&apos;s use.
        You own the rights to all content generated for your account. We do not
        guarantee that AI-generated content will be error-free and recommend
        reviewing content before publication.
      </p>
    ),
  },
  {
    id: "responsibilities",
    number: 5,
    title: "Your Responsibilities",
    content: (
      <ul className="list-disc space-y-1 pl-5">
        <li>Provide accurate business information during onboarding</li>
        <li>Maintain the security of your account credentials</li>
        <li>Review AI-generated content for accuracy before publication</li>
        <li>
          Comply with all applicable laws regarding marketing, advertising, and
          data privacy
        </li>
        <li>Not use the Service for any unlawful purpose</li>
      </ul>
    ),
  },
  {
    id: "service-level",
    number: 6,
    title: "Service Level",
    content: (
      <p>
        We strive for 99.9% uptime for our platform. AI services are deployed
        within 48 hours of onboarding completion. We do not guarantee specific
        results (lead counts, revenue increases) as outcomes depend on many
        factors beyond our control.
      </p>
    ),
  },
  {
    id: "liability",
    number: 7,
    title: "Limitation of Liability",
    content: (
      <p>
        To the maximum extent permitted by law, Sovereign AI shall not be
        liable for any indirect, incidental, special, consequential, or
        punitive damages resulting from your use of or inability to use the
        Service. Our total liability shall not exceed the amount paid by you in
        the 12 months preceding the claim.
      </p>
    ),
  },
  {
    id: "termination",
    number: 8,
    title: "Termination",
    content: (
      <p>
        Either party may terminate this agreement at any time. Upon
        termination, your access to the Service will end at the conclusion of
        your current billing period. We will retain your data for 90 days
        post-termination.
      </p>
    ),
  },
  {
    id: "data-processing",
    number: 9,
    title: "Data Processing",
    content: (
      <p>
        Where you use the Service to process personal data of your customers
        (&ldquo;End-User Data&rdquo;), you are the data controller and
        Sovereign AI acts as a data processor. We process End-User Data solely
        to provide the services you have requested, in accordance with our{" "}
        <a
          href="/legal/privacy"
          className="text-primary underline decoration-primary/30 underline-offset-2 hover:decoration-primary"
        >
          Privacy Policy
        </a>
        . You are responsible for obtaining appropriate consent from your
        customers and ensuring your use of the Service complies with applicable
        data protection laws (including GDPR, CCPA, and CAN-SPAM).
      </p>
    ),
  },
  {
    id: "indemnification",
    number: 10,
    title: "Indemnification",
    content: (
      <p>
        You agree to indemnify and hold harmless Sovereign AI, its officers,
        employees, and agents from any claims, damages, losses, or expenses
        (including reasonable attorneys&apos; fees) arising from: (a) your use
        of the Service, (b) your violation of these terms, (c) your violation
        of any applicable law, or (d) AI-generated content published by you
        without adequate review.
      </p>
    ),
  },
  {
    id: "governing-law",
    number: 11,
    title: "Governing Law & Dispute Resolution",
    content: (
      <p>
        These terms are governed by the laws of the State of Arizona, without
        regard to its conflict of law provisions. Any disputes arising under
        these terms shall first be subject to good-faith negotiation. If
        unresolved within 30 days, disputes shall be resolved by binding
        arbitration in Maricopa County, Arizona, under the rules of the
        American Arbitration Association. Nothing in this section prevents
        either party from seeking injunctive relief in a court of competent
        jurisdiction.
      </p>
    ),
  },
  {
    id: "changes",
    number: 12,
    title: "Changes to Terms",
    content: (
      <p>
        We may update these terms from time to time. We will notify you of
        material changes via email at least 30 days before the changes take
        effect. Continued use of the Service after the effective date
        constitutes acceptance of the updated terms. If you disagree with any
        changes, you may cancel your subscription before the effective date.
      </p>
    ),
  },
  {
    id: "contact",
    number: 13,
    title: "Contact",
    content: (
      <p>
        For questions about these terms, contact us at{" "}
        <a
          href="mailto:legal@trysovereignai.com"
          className="text-primary underline decoration-primary/30 underline-offset-2 hover:decoration-primary"
        >
          legal@trysovereignai.com
        </a>
        .
      </p>
    ),
  },
];

export default function TermsPage() {
  return (
    <LegalPageLayout
      title="Terms of Service"
      lastUpdated="March 28, 2026"
      sections={sections}
    />
  );
}
